---
title: "Análise Exploratória dos dados do COVID-19"
author: "Rafael Barbosa"
date: "15/03/2020"
always_allow_html: true
output:
  github_document:
    fig_width: 10
    fig_height: 6
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(fig.align = "center", out.width = "100%")

```


## Pacotes utilizados

```{r pacotes, echo = TRUE, warning = FALSE, message = F}

if(!require(tidyverse)) {
  install.packages("tidyverse", dependencies = T);
  require(tidyverse)
}

if(!require(reshape2)) {
  install.packages("reshape2", dependencies = T);
  require(reshape2)
}

if(!require(DT)) {
  install.packages("DT", dependencies = T);
  require(DT)
}

if(!require(gganimate)) {
  install.packages("gganimate", dependencies = T);
  require(gganimate)
}


if(!require(RColorBrewer)) {
  install.packages("RColorBrewer", dependencies = T);
  require(RColorBrewer)
}

if(!require(gifski)) {
  install.packages("gifski", dependencies = T);
  require(gifski)
}

```


## Configurações adicionais

A `formato_real_graf` vêm do [stackoverflow](https://pt.stackoverflow.com/questions/216852/adicionar-nota%C3%A7%C3%A3o-de-moeda-em-r).


```{r configs_adicionais} 


formato_real_graf <- function(values, nsmall = 0) { #- Formatando o valor como moeda
  values %>%
    as.numeric() %>%
    format(nsmall = nsmall, decimal.mark = ",", big.mark = ".") %>%
    str_trim()
}

```


## Carregando o banco de dados


Os dados estão disponíveis em <https://www.kaggle.com/unanimad/corona-virus-brazil>.


```{r carregando_dados, warning = F, message = F}

banco <- read_csv(file = "brazil_covid19.csv")


banco %>% 
  datatable(class = "cell-border stripe", rownames = F, 
            filter = 'top', 
            options = list(pageLength = 5, autoWidth = TRUE)) %>% 
  formatStyle(1:6, color = "black")

```


## Manuseio dos dados (by: Professora Terezinha)


### Renomear as colunas


```{r estrutura_dados}

banco <- 
  banco %>% 
  magrittr::set_colnames(c("Data", "Hora", "Estado", "Casos Suspeitos",
                           "Casos Negativos", "Casos Positivos")) 


banco %>% 
  datatable(class = "cell-border stripe", rownames = F, 
            filter = 'top', 
            options = list(pageLength = 5, autoWidth = TRUE)) %>% 
  formatStyle(columns = 1:6, color = "black")


```


## Análise Exploratória de Dados (EDA) 


### Casos suspeitos, negativos e positivos por estado (16/03)

```{r eda1}

banco %>% 
  filter(Data == max(banco$Data)) %>% 
  group_by(Estado) %>% 
  summarise(soma_suspeitos = sum(`Casos Suspeitos`),
            soma_negativos = sum(`Casos Negativos`),
            soma_positivos = sum(`Casos Positivos`))  %>% 
  magrittr::set_colnames(c("Estado", "Casos Suspeitos", "Casos Negativos",
                           "Casos Positivos"))  %>% 
  datatable(class = "cell-border stripe", rownames = F, 
            filter = 'top', 
            options = list(pageLength = 5, autoWidth = TRUE)) %>% 
  formatStyle(columns = 1:4, color = "black")


### `r format(Sys.time(), '%d de %B, %Y às %H:%M')`

```



### 4.2 - Série temporal do COVID-19



```{r eda2}

ts_gif <- 
  banco %>% 
  reshape2::melt(1:3) %>% 
  group_by(Data, variable) %>%
  summarise(soma = sum(value)) %>% 
  magrittr::set_colnames(c("Data", "Variável", "Soma")) %>% 
  mutate(Dia = lubridate::day(x = Data),
         `Mês` = lubridate::month(x = Data)) %>% 
  ggplot(data = ., aes(x = Data, y = Soma, group = `Variável`,
                       colour = `Variável`)) +
  geom_line(size = 1.15) +
  geom_point(size = 1.15) +
  scale_x_date(date_breaks = "3 day", date_labels = "%d\n%b") +
  scale_y_continuous(labels = formato_real_graf) +
  theme_bw() +
  theme(legend.position = "bottom",
        axis.title.y = element_text(colour = "black", face = "bold",
                                    size = 14),
        axis.title.x = element_text(colour = "black", face = "bold",
                                    size = 14),
        axis.text = element_text(colour = "black", size = 14),
        strip.text.x = element_text(size = 12, colour = "black", 
                                    face = "bold"),
        strip.text.y = element_text(size = 12, colour = "white"),
        legend.title = element_blank(),
        legend.text = element_text(size = 16, color = "black"),
        axis.line = element_line(size = 0.5, colour = "black")) +
  labs(x = "Data", y = "Quantidade") +
  scale_colour_manual(values = c("chartreuse2", "dodgerblue2", "firebrick2")) +
  transition_reveal(Data) +
  labs(x = "Data", y = "Quantidade")

ts_gif



#--- Para salvar o gif: 

# anim_save(filename = "TS_Covid.gif", animation = ts_gif)


```

